//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrayDogs.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        public int Id { get; set; }
        public Nullable<int> IdDog { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<int> IdDoctor { get; set; }
        public string Disease { get; set; }
        public string Comment { get; set; }
        public Nullable<int> IdStatusPriem { get; set; }
    
        public virtual Dog Dog { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Priem_Status Priem_Status { get; set; }
        public virtual StatusAppointment StatusAppointment { get; set; }
    }
}
